# Generated by Django 3.1.3 on 2020-11-11 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("checkin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitor",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="plate",
            name="visitor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plates",
                to="checkin.visitor",
            ),
        ),
        migrations.AddField(
            model_name="owner",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="house",
            name="address",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="checkin.address"
            ),
        ),
        migrations.AddField(
            model_name="house",
            name="owner",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="house",
                to="checkin.owner",
            ),
        ),
        migrations.AddField(
            model_name="checkin",
            name="house",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="checkin.house"
            ),
        ),
        migrations.AddField(
            model_name="checkin",
            name="visitor",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="checkin.visitor",
            ),
        ),
    ]
